services:
  - type: web
    name: safetywatch-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: MONGO_URI
        fromContext: MONGO_URI
      - key: JWT_SECRET
        fromContext: JWT_SECRET
